import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "@/app/theme-config.css";
import '@/app/globals.css';
import { Theme } from '@radix-ui/themes';
import NavBar from "./navbar";

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
      <Theme accentColor="iris">
       <NavBar />
       <main className="p-5">{children}</main> 
      </Theme>
      </body>
    </html>
  );
}
